#!/bin/bash

mkdir -p \
      cassandra/logs \
      cassandra/data \
      cassandra/data/data \
      cassandra/data/commitlog \
      cassandra/data/saved_caches

CASSANDRA_HOME="`pwd`/cassandra"

cassandra -f -p$CASSANDRA_HOME/pid \
  -Dcassandra.config=file://$CASSANDRA_HOME/cassandra.yaml \
  -Dcassandra.logdir=$CASSANDRA_HOME/logs \
  -Dcassandra.storagedir=$CASSANDRA_HOME/data
